name: granny_autonoumus
description: Granny.AI prototype - animated dashboard (V1)
publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.0
  vector_math: ^2.1.1
  permission_handler: ^11.1.0
  #just_audio: ^0.9.38
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.5
  http: ^1.6.0
  livekit_client: ">=2.4.2 <2.6.0"
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
